### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by arushsharma24** [dynopii/pyvirtualaudiocable#1]
Hey! I wanted to work on this project for this WoC as it seems like a pretty cool and I guess I would be learning a lot through it. However, it seems like it could be a complicated project and wanted to know what all technologies I should know since I was looking to know something more detailed than what is already mentioned in the pre-requisites (like maybe some frameworks or level of fluency in Python), so that I would be able to make meaningful contributions to this project.

(P.S. I preferred writing it here instead of emailing so anyone else who is interested and might have the same doubt can be helped)

**Comment by PhyAMR** [comment]
Hi, I want to use this tool but I still don't know how to, could you add any thing on how to use it? A python script using in it as a example? Also which library is audioop, I could not mange to find it
