### ISSUE TITLE
cant run the python script

### ISSUE THREAD

**Issue by 0lm** [dynopii/pyvirtualaudiocable#4]
hi there! i was looking for an opensource alternative to add a few virtual audio cables. so i was excited to test out this one. unfortunately i cant run it somehow. does it have any dependencies i am missing? i will copy and paste the error i get in here, maybe you can figure out what i am doing wrong. thanks in advance! I am using Windows 10 btw. what i did to try to start the file, is: "python dynopii.py"

```
Initiating dynopii virtual audio cable ...
Traceback (most recent call last):
  File "D:\Users\USERNAME\Desktop\python stuff\dynopii.py", line 9, in <module>
    subprocess.Popen(loadcmd)
  File "D:\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified 
```

**Comment by xprilion** [comment]
Hey @0lm, thanks for pointing this out. 

The project is still at a very early stage and currently we're only focusing on Linux systems. We'll be working on Windows support as soon as we have things smoothed out with Linux and our understanding of the challenges in this software grows deeper.

Do check back on us in some time!

**Comment by 0lm** [comment]
I see, thanks for the reply!
